title: LEMIFFE
tagline: Music, Software & Stories
description: "Welcome to lemiffe.com, you can find links to most of my online presence in the About section!"
url: https://lemiffe.com
baseurl: ""
paginate: 5
paginate_path: /blog/page:num/
permalink: /:title

author:
    name: Lemiffe
    url: https://twitter.com/lemiffe

plugins:
    - jekyll-paginate

version: 1.1.0
google_analytics_id: #UA-XXXX-Y
